CREATE TABLE IF NOT EXISTS "public"."comments" (
  "id" bigint NOT NULL,
  "created_at" timestamp
  with
    time zone DEFAULT now () NOT NULL,
    "post_id" bigint,
    "user_id" uuid,
    "content" text,
    "likes" bigint
);

ALTER TABLE comments ADD CONSTRAINT fk_comments FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE "public"."comments"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."comments_id_seq" START
  WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

alter table "public"."comments" enable row level security;

create policy "comments is public" on "public"."comments" for
select
  using (true);

create policy "Users can post a comment" on "public"."posts" for insert to authenticated
with
  check (
    (
      select
        auth.uid ()
    ) = user_id
  );

CREATE POLICY "Users can delete their comments" ON "public"."comments" FOR DELETE USING ((user_id = (auth.uid ())));
